apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris-api-deployment
  labels:
    app: iris-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iris-api
  template:
    metadata:
      labels:
        app: iris-api
    spec:
      containers:
        - name: iris-api
          image: us-central1-docker.pkg.dev/mlopsweek1/iris-repo/iris-api:latest
          ports:
            - containerPort: 8200

---
apiVersion: v1
kind: Service
metadata:
  name: iris-api-service
spec:
  selector:
    app: iris-api
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8200
