apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris-api-deployment
spec:
  replicas: 2 # Run 2 instances for availability
  selector:
    matchLabels:
      app: iris-api
  template:
    metadata:
      labels:
        app: iris-api
    spec:
      containers:
      - name: iris-api-container
        # IMPORTANT: Replace with your Artifact Registry path
        image: us-central1-docker.pkg.dev/mlopsweek1/iris-repo/iris-api:latest
        ports:
        - containerPort: 8000
        readinessProbe: # Checks if the app is ready to receive traffic
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe: # Checks if the app is still running
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: iris-api-service
spec:
  type: LoadBalancer # Creates an external IP address
  selector:
    app: iris-api
  ports:
  - protocol: TCP
    port: 80 # The port the service is exposed on
    targetPort: 8000 # The port the container is listening on
